services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: task-manager-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - task-manager-network
        depends_on:
            - db
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8000:80"

    db:
        image: postgres:14
        container_name: task-manager-db
        restart: unless-stopped
        networks:
            - task-manager-network
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - db_data:/var/lib/postgresql/data

    nginx:
        image: nginx:alpine
        container_name: task-manager-nginx
        restart: unless-stopped
        networks:
            - task-manager-network
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

networks:
    task-manager-network:
        driver: bridge

volumes:
    db_data:
        driver: local
